// Single source of truth for verified business facts.
// Every value here traces to the client fact sheet, the interview transcript,
// the GBP evidence, BBB, or GAF. Nothing is invented.

export const BIZ = {
  name: 'Champion Roofing',
  legalName: 'Champion Roofing LLC',
  url: 'https://championroofingok.com',
  phone: '(405) 841-7663',
  phoneRaw: '+14058417663',
  email: 'info@championroofingok.com',
  street: '7608 N Council Rd',
  city: 'Oklahoma City',
  state: 'OK',
  zip: '73132',
  owner: 'Mike Cowan',
  founded: 2004,
  foundedISO: '2004-04',
  years: 22,
  license: '80003787',
  opens: '09:00',
  closes: '17:00',
  reviewCount: 59,
  rating: '5.0',
  // Exact coordinates from the Google Maps listing URL.
  geo: { lat: 35.5487969, lng: -97.6540774 },
  mapsUrl: 'https://www.google.com/maps/search/Champion+Roofing+7608+N+Council+Rd+Oklahoma+City+OK+73132',
  // Google's own one click review form. The CID comes from the listing URL Aida
  // supplied (the hex pair after '!1s' is the place reference; the second half
  // is the CID in hex). This opens the write review dialog directly.
  writeReviewUrl: 'https://www.google.com/maps/place/?cid=5184872069979565380&action=review',
  placeUrl: 'https://www.google.com/maps/place/Champion+Roofing/@35.5487969,-97.6540774,846m/data=!3m2!1e3!4b1!4m6!3m5!1s0x87b20f8e7eb4d209:0x47f45dad50f9ed44!8m2!3d35.5487969!4d-97.6540774!16s%2Fg%2F113dqprw8',
  facebook: 'https://www.facebook.com/ChampionRoofingExteriors',
  instagram: 'https://www.instagram.com/champion_roofing/',
  sameAs: [
    'https://www.facebook.com/ChampionRoofingExteriors',
    'https://www.instagram.com/champion_roofing/',
    'https://www.bbb.org/us/ok/oklahoma-city/profile/roofing-contractors/champion-roofing-llc-0995-90020878',
    'https://www.gaf.com/en-us/roofing-contractors/commercial/champion-roofing-llc-oklahoma-city-ok-1004201',
  ],
  description:
    'Champion Roofing is a GAF Master Elite and DaVinci Masterpiece roofing contractor in Oklahoma City, installing and repairing residential, commercial and specialty roofs across the metro since 2004.',
  footerBlurb:
    'A GAF Master Elite and DaVinci Masterpiece roofing contractor based on North Council Road in Oklahoma City. Owner Mike Cowan roofed houses himself before he started the company in 2004.',
  legalNote:
    'Champion Roofing is a licensed Oklahoma roofing contractor. Roof assessments are provided at no cost and with no obligation. Insurance outcomes are determined by your carrier and adjuster, not by Champion Roofing.',

  credentials: [
    'GAF Master Elite Residential Roofing Contractor',
    'GAF Certified Commercial Contractor',
    'GAF CoatingsPro Liquid Applied Roofing Contractor',
    'GAF-listed FORTIFIED Roof contractor',
    'DaVinci Masterpiece Contractor',
    'BBB Accredited Business with an A+ rating',
  ],

  cities: [
    { name: 'Oklahoma City', x: 50, y: 50, note: 'Home base, on North Council Road' },
    { name: 'Edmond', x: 62, y: 26, note: 'North metro' },
    { name: 'Norman', x: 60, y: 84, note: 'South metro' },
    { name: 'Moore', x: 56, y: 71, note: 'South metro' },
    { name: 'Midwest City', x: 74, y: 52, note: 'East metro' },
    { name: 'Del City', x: 68, y: 60, note: 'East metro' },
    { name: 'Yukon', x: 26, y: 47, note: 'West metro' },
    { name: 'Mustang', x: 30, y: 63, note: 'Southwest metro' },
    { name: 'Bethany', x: 37, y: 44, note: 'Northwest metro' },
  ],
};

// Verified trust facts for the ticker. Each traces to a source.
export const TICKER = [
  'Roofing Oklahoma City since 2004',
  'GAF Master Elite contractor',
  'DaVinci Masterpiece contractor',
  '2021 DaVinci Project of the Year',
  '2023 DaVinci Project of the Year',
  'BBB accredited, A+ rating',
  '5.0 rating across 59 Google reviews',
  'Two year written workmanship warranty',
  'Drone assisted roof inspections',
  'First Brava synthetic roof installed in Oklahoma',
];

export const SERVICE_MENU = {
  residential: [
    { label: 'Residential roofing', path: '/residential-roofing' },
    { label: 'Roof repair', path: '/roof-repair' },
    { label: 'Roof replacement', path: '/roof-replacement' },
    { label: 'Roof inspection', path: '/roof-inspection' },
    { label: 'Storm and hail damage', path: '/storm-damage-roof-repair' },
    { label: 'Metal roofing', path: '/metal-roofing' },
    { label: 'Specialty and tile roofing', path: '/specialty-roofing' },
  ],
  commercial: [
    { label: 'Commercial roofing', path: '/commercial' },
    { label: 'TPO roofing', path: '/commercial/tpo-roofing' },
    { label: 'Seamless gutters', path: '/gutters' },
    { label: 'Window replacement', path: '/window-replacement' },
    { label: 'Our work', path: '/our-work' },
    { label: 'Service areas', path: '/service-areas' },
    { label: 'Contact', path: '/contact' },
  ],
};

export const NAV = [
  {
    label: 'Residential',
    path: '/residential-roofing',
    hubLabel: 'All residential roofing',
    note: 'Not sure what your roof needs? Book an assessment and we will tell you straight.',
    children: [
      { label: 'Roof repair', path: '/roof-repair', icon: 'wrench', blurb: 'Leaks, missing shingles, flashing and penetrations' },
      { label: 'Roof replacement', path: '/roof-replacement', icon: 'hammer', blurb: 'Tear off, decking, and a complete new system' },
      { label: 'Roof inspection', path: '/roof-inspection', icon: 'drone', blurb: 'Drone assisted, three laps, emailed report' },
      { label: 'Storm and hail damage', path: '/storm-damage-roof-repair', icon: 'storm', blurb: 'Damage assessment and insurance paperwork' },
      { label: 'Metal roofing', path: '/metal-roofing', icon: 'metal', blurb: 'Standing seam, metal shingle and corrugated' },
      { label: 'Specialty and tile', path: '/specialty-roofing', icon: 'tile', blurb: 'Clay, concrete, slate, shake and synthetics' },
      { label: 'Seamless gutters', path: '/gutters', icon: 'gutter', blurb: 'Seamless gutters and leaf protection' },
      { label: 'Window replacement', path: '/window-replacement', icon: 'screen', blurb: 'Storm damaged windows and screens, replaced with the roof' },
    ],
  },
  {
    label: 'Commercial',
    path: '/commercial',
    hubLabel: 'All commercial roofing',
    note: 'Property managers and general contractors: we coordinate around your tenants and trades.',
    children: [
      { label: 'TPO roofing', path: '/commercial/tpo-roofing', icon: 'flat', blurb: 'Our usual recommendation for low slope' },
      { label: 'Roof coatings', path: '/commercial/roof-coatings', icon: 'shield', blurb: 'GAF CoatingsPro liquid applied systems' },
      { label: 'Roof maintenance', path: '/commercial/roof-maintenance', icon: 'calendar', blurb: 'Scheduled inspection and upkeep' },
    ],
  },
  {
    label: 'Service areas',
    path: '/service-areas',
    hubLabel: 'Every area we cover',
    note: 'Based on North Council Road in northwest Oklahoma City, working across the metro.',
    children: [
      { label: 'Oklahoma City', path: '/service-areas/oklahoma-city', icon: 'house', blurb: 'Our home city, including Nichols Hills and Gaillardia' },
      { label: 'Edmond', path: '/service-areas/edmond', icon: 'ridge', blurb: 'North metro' },
      { label: 'Norman', path: '/service-areas/norman', icon: 'ridge', blurb: 'South metro' },
      { label: 'Moore', path: '/service-areas/moore', icon: 'storm', blurb: 'South metro, high storm exposure' },
      { label: 'Midwest City', path: '/service-areas/midwest-city', icon: 'ridge', blurb: 'East metro' },
      { label: 'Del City', path: '/service-areas/del-city', icon: 'ridge', blurb: 'East metro' },
      { label: 'Yukon', path: '/service-areas/yukon', icon: 'ridge', blurb: 'West metro' },
      { label: 'Mustang', path: '/service-areas/mustang', icon: 'ridge', blurb: 'Southwest metro' },
      { label: 'Bethany', path: '/service-areas/bethany', icon: 'award', blurb: 'Northwest metro, home of our award winning project' },
    ],
  },
  { label: 'Our work', path: '/our-work' },
  {
    label: 'About',
    path: '/about',
    hubLabel: 'About Champion Roofing',
    note: 'Twenty two years in Oklahoma City, and a reputation that is the whole business model.',
    children: [
      { label: 'About Champion Roofing', path: '/about', icon: 'users', blurb: 'Who we are and how we work' },
      { label: 'Reviews', path: '/reviews', icon: 'star', blurb: '5.0 across 59 Google reviews' },
      { label: 'FAQ', path: '/faq', icon: 'doc', blurb: 'Cost, insurance, warranties and timelines' },
      { label: 'Blog', path: '/blog', icon: 'leaf', blurb: 'Practical roofing advice' },
    ],
  },


  { label: 'Contact', path: '/contact' },
];

// The nine confirmed service-area cities, each with its own page.
export const CITY_PAGES = [
  {
    slug: 'oklahoma-city', name: 'Oklahoma City', position: 'Our home city',
    angle: 'Everything, from a base on North Council Road',
    lede: 'We are based here, at 7608 N Council Rd in the northwest of the city. Oklahoma City is where most of our work happens and where our specialty roofs are.',
    focus: 'specialty',
    intro: [
      'Champion Roofing has operated from North Council Road in northwest Oklahoma City since 2004. This is not a satellite service area with a rented mailbox: it is where the office is, where the crews start their day, and where most of our roofs are.',
      'It is also where our specialty work is concentrated. We have completed and maintain tile, slate and synthetic roofs in Nichols Hills, Gaillardia, Rose Creek, Cobblestone and Heritage Hills. Those streets carry a lot of DaVinci, Brava and Grand Manor product, and knowing what is already on a street matters a great deal when you are matching a repair.',
      'The 2023 DaVinci Project of the Year award was a commercial project at Gaillardia Office Park, here in the city.',
    ],
    highlights: [
      ['Our office is here.', '7608 N Council Rd, in the northwest of the city.'],
      ['Specialty roofs across the city.', 'Nichols Hills, Gaillardia, Rose Creek, Cobblestone and Heritage Hills.'],
      ['Award winning commercial work.', 'Gaillardia Office Park, DaVinci Project of the Year 2023.'],
      ['Residential and commercial.', 'From small repairs to full designer slate installations.'],
    ],
    image: 'real-luxury-brick-home',
    alt: 'A brick and stone Oklahoma City home with a designer shingle roof installed by Champion Roofing',
    image2: 'real-french-brick-estate',
    alt2: 'A large brick estate in Oklahoma City with a new architectural shingle roof',
    image3: 'res-luxury-aerial',
    alt3: 'Aerial view of a large Oklahoma City home with a complex roof',
    seoTitle: "Oklahoma City Roofer | Specialty, Tile and Slate | Champion",
    seoDesc: "Champion Roofing is based on N Council Rd in Oklahoma City: tile, slate and synthetic specialists, plus repair, replacement and gutters across the metro.",
    picks: ["/roof-replacement","/roof-repair","/commercial"],
    faqs: [
      { q: "Where in Oklahoma City is Champion Roofing based?", a: "At 7608 N Council Rd in the northwest of the city, where the office and the crews start every day. It is not a satellite address.\n\nMost of our specialty tile, slate and synthetic work is concentrated here too: Nichols Hills, Gaillardia, Rose Creek, Cobblestone and Heritage Hills all carry roofs we installed or maintain." },
      { q: "Do you do the high end tile and slate roofs in Nichols Hills and Gaillardia?", a: "Yes, and it is most of what we are known for. Those streets carry a lot of DaVinci, Brava and Grand Manor product, and knowing what is already on a street matters a great deal when you are matching a repair.\n\nOur 2023 DaVinci Project of the Year was at Gaillardia Office Park, here in the city." },
      { q: "Is the roof assessment free in Oklahoma City?", a: "Yes. No cost, no obligation, and no charge if the answer is that your roof is fine. An inspector flies the roof with a drone in three passes, talks the findings through on site, and emails you a written report either way." },
      { q: "Do you handle insurance claims for Oklahoma City homes?", a: "On the roofing side, yes. We document the damage across every elevation, meet your adjuster at the property, and work through the approved scope with your carrier.\n\nWe cannot decide the outcome. Your carrier does that, and anyone who guarantees you an approval is telling you something they cannot know." },
    ],
  },
  {
    slug: 'edmond', name: 'Edmond', position: 'North metro',
    angle: 'Roof replacement and designer shingle work',
    lede: 'Edmond sits directly north of our Council Road office, which makes it one of the easiest parts of the metro for us to schedule and to come back to.',
    focus: 'replacement',
    intro: [
      'Edmond is a straightforward run north from our office, and proximity matters more than it sounds like it should. A roofing warranty is only worth what the company behind it can actually service, and being close by is part of what makes coming back a small thing rather than a big one.',
      'Most of what we do in Edmond is full roof replacement and higher end shingle work. Colour and profile selection comes up more here than almost anywhere, which is consistent with our reviews: five separate Google reviews mention colour options specifically.',
      'We also handle the storm work that follows a hail event, including meeting your adjuster at the property.',
    ],
    highlights: [
      ['A short run from the office.', 'Directly north of North Council Road.'],
      ['Replacement and designer shingle.', 'Including architectural and designer profiles.'],
      ['Colour guidance that is actually useful.', 'How it will read on your house and your street.'],
      ['Storm and insurance support.', 'We document the damage and meet the adjuster.'],
    ],
    image: 'res-luxury-aerial',
    alt: 'Aerial view of a large home with a complex roof in the north Oklahoma City metro',
    image2: 'res-tan-new-roof',
    alt2: 'A tan brick home with a newly installed shingle roof',
    image3: 'res-dormers-grey',
    alt3: 'A grey shingle roof with a row of dormers',
    seoTitle: "Edmond OK Roof Replacement and Designer Shingles | Champion",
    seoDesc: "Roof replacement and designer shingle work in Edmond, a short run north of our Oklahoma City office. Colour guidance, storm work, free drone assessments.",
    picks: ["/roof-replacement","/storm-damage-roof-repair","/roof-inspection"],
    faqs: [
      { q: "How far is Edmond from your office?", a: "A straightforward run north from North Council Road. That matters more than it sounds: a warranty is only worth what the company behind it can actually service, and being close by makes coming back a small thing rather than a big one." },
      { q: "What do you do most in Edmond?", a: "Full roof replacement and higher end shingle work. Colour and profile selection comes up more here than almost anywhere, which fits our reviews: five separate customers mention colour options specifically." },
      { q: "Can you help us choose a shingle colour for an Edmond house?", a: "Yes, and we try to be genuinely useful about it rather than handing over a sample board. How a colour reads on your roof pitch, against your brick, and next to the houses either side is something we look at with you on site." },
      { q: "Do you handle hail claims in Edmond?", a: "Yes. We document the damage, meet your adjuster at the property, and work through the scope with your carrier. The decision itself belongs to your insurer, not to us." },
    ],
  },
  {
    slug: 'norman', name: 'Norman', position: 'South metro',
    angle: 'Inspections and roof repair',
    lede: 'Norman is the southern end of our service area. We work there regularly, and we will tell you honestly if a job is better suited to somebody closer.',
    focus: 'inspection',
    intro: [
      'Norman is the furthest regular run we make, at the southern end of the metro. We work there and we are happy to, but we will also say plainly when a very small job would be better handled by somebody based closer to you. That is a more useful answer than a padded quote.',
      'The work we do most in Norman is inspection and repair. A free drone assessment costs you nothing and gives you a written record of the roof condition, which is worth having whether or not anything needs doing.',
      'For a full replacement or a specialty roof, distance stops mattering: those are projects we plan properly and staff accordingly.',
    ],
    highlights: [
      ['Free drone inspections.', 'Three laps, findings on site, report by email.'],
      ['Repairs and full replacements.', 'Both, with the same warranty as anywhere else.'],
      ['An honest answer about fit.', 'If we are the wrong people for a small job, we will say so.'],
      ['Storm documentation.', 'For claims after a hail or wind event.'],
    ],
    image: 'hail-chalk-marks-grey',
    alt: 'Hail impact marks circled in chalk during a roof inspection',
    image2: 'crew-ladder-ranch',
    alt2: 'A roofing crew working from a ladder on a single storey home',
    image3: 'res-white-house-dark-roof',
    alt3: 'A white house with a dark shingle roof among trees',
    seoTitle: "Norman OK Roof Inspection and Repair | Champion Roofing",
    seoDesc: "Free drone roof inspections and honest repair advice in Norman, at the south end of the metro. If a small job suits someone closer, we will say so.",
    picks: ["/roof-inspection","/roof-repair","/roof-replacement"],
    faqs: [
      { q: "Do you really come out to Norman?", a: "Yes, regularly. Norman is the furthest regular run we make, at the south end of the metro. For a very small job we will sometimes tell you that somebody based closer to you is the better fit, because that is a more useful answer than a padded quote." },
      { q: "What is the inspection like in Norman?", a: "A free drone survey in three passes, findings talked through on site, and a written report by email whether or not anything needs doing. It costs you nothing and gives you a record of the roof condition." },
      { q: "Will you do a full replacement in Norman?", a: "Yes. For a full replacement or a specialty roof, distance stops mattering: those are projects we plan properly and staff accordingly, and the warranty is the same as anywhere else." },
      { q: "Do you help with storm claims in Norman?", a: "We document the damage and meet your adjuster on site. Your carrier decides the outcome; we make the case." },
    ],
  },
  {
    slug: 'moore', name: 'Moore', position: 'South metro',
    angle: 'Storm and hail damage',
    lede: 'Moore takes serious weather. Most of what we are called out for here follows a storm, and that means documentation and insurance work as much as roofing.',
    focus: 'storm',
    intro: [
      'Moore sits in a part of the metro that takes severe weather seriously, and most of the calls we get from there follow an event rather than precede one. That shapes the job: before anything gets fixed, the damage has to be documented properly.',
      'Our inspector flies the roof in three passes and covers more than the shingles. Soft metals, gutters, window screens and fencing all mark under hail that a shingle absorbs invisibly, and together they establish what the storm actually did. We are at the property when your adjuster comes out.',
      'What we will not do is promise you an approval. Your carrier decides that. We document, we make the case, and we tell you honestly if we think your roof was not damaged, even when the whole street is being replaced.',
    ],
    highlights: [
      ['Storm damage documented properly.', 'Every elevation, plus soft metals and screens.'],
      ['We meet your adjuster on site.', 'So the conversation includes someone who has been on the roof.'],
      ['Class 4 impact rated options.', 'Where it makes sense for the exposure here.'],
      ['No promises about your claim.', 'That decision belongs to your insurer, not to us.'],
    ],
    image: 'storm-tarp-crew',
    alt: 'A roofing crew fitting a protective tarp over a storm damaged roof',
    image2: 'storm-tree-on-roof',
    alt2: 'A fallen tree resting on a storm damaged residential roof',
    image3: 'res-skylight-dark',
    alt3: 'A dark shingle roof with a skylight',
    seoTitle: "Moore OK Storm and Hail Roof Repair | Champion Roofing",
    seoDesc: "Storm and hail damage roofing in Moore. Drone documentation of every elevation, we meet your adjuster on site, and no promises about your claim.",
    picks: ["/storm-damage-roof-repair","/roof-inspection","/roof-replacement"],
    faqs: [
      { q: "Why is so much of your Moore work storm related?", a: "Because Moore takes serious weather, and most of the calls we get from there follow an event rather than precede one. That shapes the job: before anything gets fixed, the damage has to be documented properly." },
      { q: "What do you document after a hail storm in Moore?", a: "Every elevation of the roof, and more than the shingles: soft metals, gutters, window screens and fencing all mark under hail that a shingle absorbs invisibly. Together they establish what the storm actually did." },
      { q: "Will you meet my adjuster in Moore?", a: "Yes, at the property, so the conversation includes someone who has actually been on the roof." },
      { q: "Can you promise my claim will be approved?", a: "No, and neither can anyone else honestly. Your carrier decides that. We document, we make the case, and we will tell you if we think your roof was not damaged, even when the whole street is being replaced." },
    ],
  },
  {
    slug: 'midwest-city', name: 'Midwest City', position: 'East metro',
    angle: 'Repairs, replacement and multifamily',
    lede: 'Midwest City is an easy run east from the office. We do residential repair and replacement there, and a fair amount of multifamily work.',
    focus: 'repair',
    intro: [
      'Midwest City is a straightforward run east and we work there regularly, on houses and on multifamily property alike.',
      'Multifamily is its own discipline: more units, more coordination, tenants who need to be able to come and go, and a property manager who needs to know what is happening on which building and when. We put a foreman on site whose job includes exactly that.',
      'On the residential side the work is what it is everywhere: leaks, storm damage, lifted shingles, failed flashing, and full replacements when repair has stopped being the sensible spend.',
    ],
    highlights: [
      ['Residential repair and replacement.', 'Diagnosed before it is quoted.'],
      ['Multifamily and rental property.', 'Coordinated around tenants and access.'],
      ['A foreman on site.', 'Managing safety, materials and cleanup.'],
      ['Free assessments.', 'Same as everywhere else on this list.'],
    ],
    image: 'real-multifamily-sign',
    alt: 'A two storey multifamily building with a Champion Roofing yard sign in front',
    image2: 'comm-apartment-flat',
    alt2: 'Aerial view of a multifamily building with a low slope roof',
    image3: 'res-grey-gable-siding',
    alt3: 'A grey gabled house with new roofing and siding',
    seoTitle: "Midwest City Roofing and Multifamily Roofs | Champion",
    seoDesc: "Residential roof repair and replacement in Midwest City, plus multifamily roofing run around tenants and property managers with a foreman on site.",
    picks: ["/roof-repair","/roof-replacement","/commercial"],
    faqs: [
      { q: "Do you do apartment and multifamily roofing in Midwest City?", a: "Yes, a fair amount of it. Multifamily is its own discipline: more units, tenants who need to come and go, and a property manager who needs to know what is happening on which building and when. We put a foreman on site whose job includes exactly that." },
      { q: "What residential work do you do in Midwest City?", a: "Leaks, storm damage, lifted shingles, failed flashing, and full replacements when repair has stopped being the sensible spend. It is an easy run east from our office." },
      { q: "Is the assessment free for Midwest City properties?", a: "Yes, for houses and for multifamily buildings. Drone survey, findings on site, written report by email." },
      { q: "Do you work with property managers?", a: "Routinely. Coordinating around tenants, access and other trades is part of the job rather than something we hand back to the client." },
    ],
  },
  {
    slug: 'del-city', name: 'Del City', position: 'East metro',
    angle: 'Repair, gutters and honest advice',
    lede: 'Del City is next door to Midwest City in our schedule. A lot of the work here is repair and gutters rather than full replacement.',
    focus: 'gutters',
    intro: [
      'Del City sits alongside Midwest City on our schedule, in the east of the metro.',
      'The work here skews toward repair and gutters rather than full replacement, and that suits us. We would rather do a repair that is genuinely the right answer than sell a roof that is not needed yet. When a repair has stopped making sense we will tell you that too.',
      'Gutters are worth taking seriously. They are the service our customers mention most after the roof itself, and when they stop working the damage does not stay at the gutter: water backs up at the eave, gets behind the fascia and reaches the decking.',
    ],
    highlights: [
      ['Repair first where repair is right.', 'We will tell you when it is not.'],
      ['Seamless gutters and leaf protection.', 'Formed to the run, not joined every few feet.'],
      ['Free drone assessment.', 'With a written report either way.'],
      ['Two year workmanship warranty.', 'On everything we install.'],
    ],
    image: 'gutter-downspout-white',
    alt: 'A new white seamless gutter and downspout against a clear sky',
    image2: 'gutter-worker-install',
    alt2: 'A worker installing a seamless gutter along a roof eave',
    image3: 'res-craftsman-gables',
    alt3: 'A craftsman style home with steep shingled gables',
    seoTitle: "Del City Roof Repair and Gutters | Champion Roofing",
    seoDesc: "Roof repair and seamless gutters in Del City, east of Oklahoma City. Repair first where repair is right, and we will tell you when it is not.",
    picks: ["/roof-repair","/gutters","/roof-inspection"],
    faqs: [
      { q: "Do you do small roof repairs in Del City?", a: "Yes, and we would rather do a repair that is genuinely the right answer than sell a roof that is not needed yet. When a repair has stopped making sense we will tell you that too." },
      { q: "Why do you push gutters so hard?", a: "We do not push them, but they matter more than they look like they do. They are the service our customers mention most after the roof itself, and when they stop working the damage does not stay at the gutter: water backs up at the eave and reaches the decking." },
      { q: "Is leaf protection worth it on a Del City house?", a: "It depends on the trees. Worth fitting where branches overhang the roof; a much weaker case where nothing does, and we will say so rather than sell it anyway." },
      { q: "What warranty comes with a Del City repair?", a: "Two years in writing on workmanship, the same as everywhere else we work." },
    ],
  },
  {
    slug: 'yukon', name: 'Yukon', position: 'West metro',
    angle: 'Metal roofing and outbuildings',
    lede: 'Yukon is a short run west. Alongside the usual residential work, this is an area where metal roofing on shops and outbuildings comes up more often.',
    focus: 'metal',
    intro: [
      'Yukon is west of our Council Road office and an easy area for us to work in.',
      'Alongside ordinary residential roofing, metal comes up more here than in some parts of the metro, particularly on shops, outbuildings and properties with longer simple roof runs. Metal suits that kind of building well: it sheds water fast and handles wind properly when it is fastened correctly.',
      'The detailing is what decides whether a metal roof lasts. Panel layout, allowance for thermal movement and the flashing at every transition get planned before anything is ordered, not resolved on the roof.',
    ],
    highlights: [
      ['Standing seam, metal shingle and corrugated.', 'Specified to the building.'],
      ['Outbuildings and shops.', 'Not only houses.'],
      ['Full residential roofing too.', 'Shingle, tile and everything else we install.'],
      ['Honest material advice.', 'Including when metal is the wrong answer for your roof.'],
    ],
    image: 'metal-standing-seam-commercial',
    alt: 'A standing seam metal roof on a commercial building',
    image2: 'crew-metal-scaffold',
    alt2: 'A crew installing metal roof panels with scaffolding in place',
    image3: 'metal-dark-chimney-field',
    alt3: 'A dark metal roof with a chimney against open country',
    seoTitle: "Yukon OK Metal Roofing and Outbuildings | Champion Roofing",
    seoDesc: "Metal roofing for shops, outbuildings and homes in Yukon, west of Oklahoma City. Standing seam, metal shingle and corrugated, detailed to last.",
    picks: ["/metal-roofing","/roof-replacement","/roof-repair"],
    faqs: [
      { q: "Why does metal come up so much in Yukon?", a: "More shops, outbuildings and properties with long simple roof runs than in some parts of the metro. Metal suits that kind of building well: it sheds water fast and handles wind properly when it is fastened correctly." },
      { q: "What decides whether a metal roof lasts?", a: "The detailing, not the panel. Panel layout, allowance for thermal movement and the flashing at every transition get planned before anything is ordered, not resolved on the roof." },
      { q: "Do you still do ordinary shingle roofs in Yukon?", a: "Of course. Full residential roofing, repair, replacement and inspection, same as anywhere on our list. Metal is simply the thing that comes up here more often." },
      { q: "Will you tell me if metal is wrong for my roof?", a: "Yes. There are roofs where it is the wrong answer on cost, on look or on the building, and we would rather say so than sell it." },
    ],
  },
  {
    slug: 'mustang', name: 'Mustang', position: 'Southwest metro',
    angle: 'Replacement and new construction',
    lede: 'Mustang is southwest of the city. We do a good deal of full replacement and new construction roofing here.',
    focus: 'replacement',
    intro: [
      'Mustang sits southwest of Oklahoma City and is a regular part of our working area.',
      'A lot of what we do here is full roof replacement and roofing on new construction, including detached structures and covered outdoor spaces. New construction is a different rhythm from a re roof: the coordination matters more, because we are one trade among several and the schedule has to hold.',
      'On replacements, the commitment is the same one we make everywhere. The price we quote is the price you pay, and if we hit something mid job we generally absorb it rather than sending you a change order.',
    ],
    highlights: [
      ['Full roof replacement.', 'Complete tear off, decking reported honestly.'],
      ['New construction roofing.', 'Coordinated with the other trades on site.'],
      ['The price is the price.', 'No change order games.'],
      ['Two year written workmanship warranty.', 'Plus transferable manufacturer options.'],
    ],
    image: 'real-timber-pavilion',
    alt: 'A timber framed pavilion with a newly installed shingle roof',
    image2: 'install-hand-shingles',
    alt2: 'A roofer hand laying shingles across a new roof deck',
    image3: 'res-shake-gable',
    alt3: 'A shake style gable roof on a residential property',
    seoTitle: "Mustang OK Roof Replacement and New Construction | Champion",
    seoDesc: "Full roof replacement and new construction roofing in Mustang, southwest of Oklahoma City. The price we quote is the price you pay.",
    picks: ["/roof-replacement","/roof-repair","/gutters"],
    faqs: [
      { q: "Do you do new construction roofing in Mustang?", a: "Yes, including detached structures and covered outdoor spaces. New construction has a different rhythm from a re roof: we are one trade among several and the schedule has to hold, so the coordination matters more." },
      { q: "Will the price change once a Mustang replacement starts?", a: "That is not how we work. The price we quote is the price you pay, and if we hit something mid job we generally absorb it rather than sending you a change order. The exception is something nobody could have known about, and you hear about it before anything is done." },
      { q: "What does a Mustang replacement involve?", a: "Complete tear off, the deck inspected and reported honestly, underlayment, flashing, covering, ridge and ventilation in order, then a magnet sweep and the warranty paperwork." },
      { q: "What warranty do I get?", a: "Two years in writing on workmanship from us, with transferable manufacturer options available to qualifying customers." },
    ],
  },
  {
    slug: 'bethany', name: 'Bethany', position: 'Northwest metro',
    angle: 'Close to home, and the site of our award winning project',
    lede: 'Bethany is essentially next door to our office. It is also home to Bethany Children\'s Health Center, where we did the project that won DaVinci Project of the Year in 2021.',
    focus: 'specialty',
    intro: [
      'Bethany borders the northwest part of Oklahoma City where our office sits, which makes it one of the closest areas we work in.',
      'It is also where our 2021 DaVinci Roofscapes Masterpiece Contractor Project of the Year award came from: a commercial project at the Donald W. Reynolds Complex at Bethany Children\'s Health Center. Mike Cowan, who owns Champion Roofing, serves on the board and the building committee there.',
      'So this is not a service area we added to a list. It is a few minutes from the office and it is where one of the projects we are proudest of stands.',
    ],
    highlights: [
      ['Minutes from our office.', 'Bordering northwest Oklahoma City.'],
      ['DaVinci Project of the Year 2021.', 'Donald W. Reynolds Complex, Bethany Children\'s Health Center.'],
      ['Our owner is on the board there.', 'Board and building committee, Bethany Children\'s Health Center.'],
      ['Residential and commercial.', 'Including specialty tile and synthetic roofing.'],
    ],
    image: 'real-commercial-campus',
    alt: 'A large commercial campus building with a Champion Roofing installed roof',
    image2: 'specialty-clay-tile-home',
    alt2: 'A specialty clay tile roof on a large residence',
    image3: 'res-dormer-blue-sky',
    alt3: 'A dormer window and shingle roof against a blue sky',
    seoTitle: "Bethany OK Roofing | 2021 Award Project | Champion",
    seoDesc: "Roofing in Bethany, minutes from our office and home to our 2021 DaVinci Project of the Year at Bethany Children's Health Center.",
    picks: ["/specialty-roofing","/roof-replacement","/commercial"],
    faqs: [
      { q: "What is the award winning project in Bethany?", a: "Our 2021 DaVinci Roofscapes Masterpiece Contractor Project of the Year: a commercial project at the Donald W. Reynolds Complex at Bethany Children's Health Center. Mike Cowan, who owns Champion Roofing, serves on the board and building committee there." },
      { q: "How close is Bethany to your office?", a: "It borders the northwest part of Oklahoma City where we are based, which makes it one of the closest areas we work in. A few minutes from the door." },
      { q: "Do you do residential work in Bethany, or just commercial?", a: "Both, including specialty tile and synthetic roofing. The award project happens to be commercial; most of what we do in Bethany is houses." },
      { q: "Is the assessment free in Bethany?", a: "Yes. Drone survey, findings on site, written report by email, no charge either way." },
    ],
  },
];

// Options offered in the lead form service picker.
export const SERVICE_OPTIONS = [
  'Roof inspection or assessment',
  'Roof repair',
  'Roof replacement',
  'Storm or hail damage',
  'Metal roofing',
  'Specialty or tile roofing',
  'Commercial roofing',
  'Seamless gutters',
  'Window screen replacement',
  'Something else',
];

// Review themes drawn from the supplied GBP analysis. Presented as aggregate
// evidence, never as fabricated quotes attributed to named people.
export const REVIEW_THEMES = [
  { label: 'Gutters', count: 13 },
  { label: 'Timely manner', count: 7 },
  { label: 'Gutter replacement', count: 6 },
  { label: 'Smooth process', count: 6 },
  { label: 'Color options', count: 5 },
  { label: 'Responsive staff', count: 5 },
  { label: 'Thorough inspection', count: 4 },
  { label: 'Shingle selection', count: 3 },
  { label: 'Local roofers', count: 3 },
];

export const REDIRECTS = [
  ['/home', '/'],
  ['/roof-inspection-residential', '/roof-inspection'],
  ['/screens', '/window-replacement'],
  ['/window-screen-repair', '/window-replacement'],
  ['/roof-repair-replacement-residential', '/roof-repair'],
  ['/roof-repair-replacement', '/roof-repair'],
  ['/commercial-roofing', '/commercial'],
  ['/roof-repair-replacement-commercial', '/commercial'],
  ['/residential', '/residential-roofing'],
  ['/roofing', '/residential-roofing'],
  ['/hail-101', '/storm-damage-roof-repair'],
  ['/blog/tag/material', '/blog'],
  ['/blog/tag/design', '/blog'],
  ['/blog/tag/Leak', '/blog'],
  ['/blog/tag/roofing', '/blog'],
  ['/blog/tag/Roofing', '/blog'],
  ['/blog/tag/Mistakes', '/blog'],
  ['/blog/tag/Repairs', '/blog'],
  ['/blog/tag/Damage', '/blog'],
];
